#!/bin/bash
set -ux

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ "$(uname)" = "Darwin" ]; then
  brew install zsh ansible
else
  sudo apt update && sudo apt install -y zsh ansible
fi


cp $DIR/zsh-wrap ~/.zshrc
ln -s $DIR/gitconfig ~/.gitconfig
ln -s $DIR/tmux.conf ~/.tmux.conf
ln -s $DIR/vimrc ~/.vimrc

hooksdir=~/.git-templates/hooks
mkdir -p $hooksdir
cp $DIR/githooks/prepare-commit-msg $hooksdir/
