#!/bin/bash
set -uxo pipefail

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
pushd $DIR

if [ "$(uname)" = "Darwin" ]; then
  brew install zsh ansible
else
  sudo apt update && sudo apt install -y ansible
fi

# TODO this could be in the ansible _shrug_
cp $DIR/zsh-wrap ~/.zshrc
rm ~/.gitconfig
cp $DIR/gitconfig-wrapper ~/.gitconfig
ln -s $DIR/tmux.conf ~/.tmux.conf
ln -s $DIR/vimrc ~/.vimrc

hooksdir=~/.git-templates/hooks
mkdir -p $hooksdir
cp $DIR/githooks/prepare-commit-msg $hooksdir/

popd
