---

- name: docker | prereqs
  apt:
    name:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
  become: yes

- name: docker | apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: yes

- name: docker | apt repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ubuntu_distro }} stable
  become: yes

- name: docker | install
  apt:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes

- name: docker | add me to group
  user:
    append: yes
    groups:
      - docker
    name: "{{ ansible_user }}"
  become: yes
