---

- set_fact:
    distro: focal

- name: basics | common apt packages
  apt:
    name:
    - curl
    - htop
    - git
    - git-lfs
    - hub
    - inotify-tools
    - meld
    - ncdu
    - nmap
    - openssh-server
    - python3-pip
    - screen
    - snap
    - tmux
    - tree
    - vim
    - zsh
  become: yes

- name: basics | pip upgrade
  pip:
    executable: pip3
    name: pip
    state: latest
  tags: [python]

- name: basics | install some core pip stuff
  pip:
    executable: pip3
    name:
      - ipython
      - jupyter
  tags: [python]

# TODO fix this so that we don't have to ignore errors - especially since sometimes they're real
- name: oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  ignore_errors: yes  # fails the second time
  tags: [omz]

- include_tasks: desktop.yaml
  tags: [desktop]

- include_tasks: vscode.yml
  tags: [vscode]

- include_tasks: docker.yml
  tags: [docker]

- include_tasks: vivaldi.yml
  tags: [vivaldi]
