---

- set_fact:
    distro: focal

- name: basics | common apt packages
  apt:
    name:
    - curl
    - htop
    - git
    - hub
    - inotify-tools
    - meld
    - openssh-server
    - python3-pip
    - screen
    - snap
    - tmux
    - tree
    - vim
    - zsh
  become: yes

- name: basics | install some core pip stuff
  pip:
    executable: pip3
    name:
      - virtualenv
      - docker-compose
      - ipython
      - jupyter

- name: atom
  include_tasks: atom.yml

- name: appearance packages
  apt:
    name:
    - gnome-tweaks
    - gnome-shell-extension-system-monitor
  become: yes

- name: docker
  include_tasks: docker.yml

- name: vivaldi browser
  include_tasks: vivaldi.yml

- name: local ros dev
  include_tasks: ros.yml

# consider snaps
# * hub
# * losslesscut
