---

- name: vscode | apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
  become: yes

- name: vscode | apt repo
  apt_repository:
    repo: deb https://packages.microsoft.com/repos/code stable main
  become: yes

- name: vscode | install
  apt:
    name: code
  become: yes
