---
- name: Download Kubernetes GPG key
  become: true
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: "0644"

- name: Add Kubernetes apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: kubernetes
    types: [deb]
    uris: "https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/"
    suites: ["/"]
    signed_by: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    state: present

- name: Install kubectl
  become: true
  ansible.builtin.apt:
    name: kubectl
    state: present
    update_cache: true
